### ISSUE TITLE
ValueError: Old is good (1.82645) and new is bad (-1.0).

### ISSUE THREAD

**Issue by pfultz2** [ROCmSoftwarePlatform/Tensile#647]
I am tuning some int8 configs and get the following error from Tensile:

```
Traceback (most recent call last):
  File "/usr/local/bin/Tensile", line 11, in <module>
    load_entry_point('Tensile==4.11.0', 'console_scripts', 'Tensile')()
  File "/usr/local/lib/python3.6/dist-packages/Tensile/Tensile.py", line 224, in main
    Tensile(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/Tensile/Tensile.py", line 181, in Tensile
    executeStepsInConfig( config )
  File "/usr/local/lib/python3.6/dist-packages/Tensile/Tensile.py", line 51, in executeStepsInConfig
    BenchmarkProblems.main( config["BenchmarkProblems"] )
  File "/usr/local/lib/python3.6/dist-packages/Tensile/BenchmarkProblems.py", line 796, in main
    problemSizeGroupConfig, problemSizeGroupIdx)
  File "/usr/local/lib/python3.6/dist-packages/Tensile/BenchmarkProblems.py", line 364, in benchmarkProblemType
    results = getResults(resultsFileName, solutions, enableTileSelection, newResultsFileName)
  File "/usr/local/lib/python3.6/dist-packages/Tensile/BenchmarkProblems.py", line 461, in getResults
    diffCSV.writerow([compareResults(old,new,name) for old,new,name in itertools.zip_longest(row, newRow, headerRow)])
  File "/usr/local/lib/python3.6/dist-packages/Tensile/BenchmarkProblems.py", line 461, in <listcomp>
    diffCSV.writerow([compareResults(old,new,name) for old,new,name in itertools.zip_longest(row, newRow, headerRow)])
  File "/usr/local/lib/python3.6/dist-packages/Tensile/BenchmarkProblems.py", line 406, in compareResults
    raise ValueError("Old is good ({}) and new is bad ({}). Name: {}".format(old, new, name))
ValueError: Old is good (1.82645) and new is bad (-1.0). Name:  Cijk_Ailk_Bljk_4xi8B_MT32x32x8_SE_EPS0_FL0_GRVW1_GSU8_LPB0_PGR0_PLR0_TT2_2_USFGRO1_VW2_WG16_16_1_WGM1
```

Here is the yaml file I am using for benchmarking:

```yaml
GlobalParameters:
  CMakeBuildType: Release
  DataInitTypeAB: 0
  DataInitTypeBeta: 0
  Device: 0
  EnqueuesPerSync: 1
  ForceRedoBenchmarkProblems: true
  ForceRedoLibraryClient: true
  ForceRedoLibraryLogic: true
  KernelTime: true
  LibraryPrintDebug: false
  MergeFiles: true
  MinimumRequiredVersion: 4.2.0
  NumElementsToValidate: 0
  PinClocks: false
  Platform: 0
  PrintWinnersOnly: 1
  ShortNames: false
  SleepPercent: 50
  SolutionSelectionAlg: 1
  SyncsPerBenchmark: 1
  ValidationMaxToPrint: 4
  ValidationPrintValids: false
BenchmarkProblems:
- - {Batched: true, DataType: 4xi8, DestDataType: I, OperationType: GEMM, TransposeA: false, TransposeB: false,
    UseBeta: true}
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [2, 1, 1, 768]
      - Exact: [768, 1, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalSplitU: [1, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
      - [32, 8, 4]
      - [8, 32, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [3072, 128, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - ThreadTile:
      - [4, 4]
      - [6, 4]
      - [4, 6]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [768, 128, 1, 3072]
      - Exact: [768, 128, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalSplitU: [1, 8]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
      - [4, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [2, 1, 1, 768]
      - Exact: [768, 1, 1, 768]
      - Exact: [2, 1, 1, 768]
      - Exact: [768, 1, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalSplitU: [1, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
      - [32, 8, 4]
      - [8, 32, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [3072, 128, 1, 768]
      - Exact: [3072, 128, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - ThreadTile:
      - [4, 4]
      - [6, 4]
      - [4, 6]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [768, 128, 1, 3072]
      - Exact: [768, 128, 1, 768]
      - Exact: [768, 128, 1, 3072]
      - Exact: [768, 128, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalSplitU: [1, 8]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
      - [4, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [128, 128, 12, 64]
      - Exact: [64, 128, 12, 128]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [4, 4]
      - [4, 2]
      - [2, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [16, 8, 1]
      - [8, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [128, 128, 12, 64]
      - Exact: [64, 128, 12, 128]
      - Exact: [128, 128, 12, 64]
      - Exact: [64, 128, 12, 128]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - PrefetchGlobalRead: [false, true]
    - PrefetchLocalRead: [false, true]
    - LdsPadA: [0, -1]
    - LdsPadB: [0, -1]
    - ThreadTile:
      - [4, 4]
      - [4, 2]
      - [2, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [16, 8, 1]
      - [8, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
LibraryLogic:
  ArchitectureName: gfx906
  DeviceNames: [Device 66a0, Device 66a1, Device 66a7, Vega 20]
  ScheduleName: vega20
LibraryClient:
```
